name: create-release

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_call:
    inputs:
      tag:
        default: '0'
        required: true
        type: string
      note:
        default: 'None'
        required: true
        type: string
    outputs:
      pushed_tag:
        description: "Pushed tag version"
        value: ${{ jobs.create-release.outputs.pushed_tag }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      pushed_tag: ${{ steps.release.outputs.pushed_tag }}
    steps:
      - uses: actions/checkout@v4
      
      - id: check-release
        name: Check if release exists
        run: |
          if gh release view $PUSH_TAG &>/dev/null; then
            echo "release_exists=true" >> $GITHUB_OUTPUT
          else
            echo "release_exists=false" >> $GITHUB_OUTPUT
          fi
        shell: bash
        env:
          PUSH_TAG: ${{ inputs.tag }}
      
      - id: release
        name: Create or update release
        run: |
          if [ "$RELEASE_EXISTS" == "true" ]; then
            echo "Release with tag $PUSH_TAG already exists, overwriting it..."
            gh release edit $PUSH_TAG --notes "$NOTE"
          else
            echo "Creating new release with tag $PUSH_TAG..."
            gh release create $PUSH_TAG --notes "$NOTE"
          fi
          echo "pushed_tag=$PUSH_TAG" >> $GITHUB_OUTPUT
        shell: bash
        env:
          PUSH_TAG: ${{ inputs.tag }}
          NOTE: ${{ inputs.note }}
          RELEASE_EXISTS: ${{ steps.check-release.outputs.release_exists }}