name: release

on:
  workflow_call:
    inputs:
      path:
        default: 'Cargo.toml'
        required: true
        type: string

jobs:
  ready:
    uses: ./.github/workflows/parse-info.yml
    with:
      path: ${{ inputs.path }}
  tag:
    needs:
      - ready
    uses: ./.github/workflows/create-tag.yml
    with:
      version: ${{ needs.ready.outputs.version }}
  release:
    needs:
      - tag
    uses: ./.github/workflows/create-release.yml
    with:
      tag: ${{ needs.tag.outputs.tag }}
      note: "add release for ${{ needs.tag.outputs.tag }}"

  matrix-release:
    uses: ./.github/workflows/build.yml
    strategy:
      matrix:
        include:
          # - target: aarch64-apple-darwin
          #   platform: macos-latest
          # - target: x86_64-apple-darwin
          #   platform: macos-latest
          # - target: x86_64-unknown-linux-gnu
          #   platform: ubuntu-latest
          # - target: aarch64-unknown-linux-gnu
          #   platform: ubuntu-latest
          # - target: powerpc64le-unknown-linux-gnu
          #   platform: ubuntu-latest
          # - target: riscv64gc-unknown-linux-gnu
          #   platform: ubuntu-latest
          # - target: s390x-unknown-linux-gnu
          #   platform: ubuntu-latest
          # - target: x86_64-pc-windows-gnu
          #   platform: windows-latest
          # - target: x86_64-pc-windows-msvc
          #   platform: windows-latest
          - target: x86_64-unknown-linux-musl
            platform: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            platform: ubuntu-latest
          - target: powerpc64le-unknown-linux-musl
            platform: ubuntu-latest
    with:
      path: ${{ inputs.path }}
      target: ${{ matrix.target }}
      platform: ${{ matrix.platform }}
